defmodule Twitter.Repo.Migrations.MigrateResources1 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:users, primary_key: false) do
      add :id, :uuid, null: false, primary_key: true
      add :email, :citext, null: false
      add :hashed_password, :text
      add :inserted_at, :utc_datetime_usec, null: false, default: fragment("now()")
      add :updated_at, :utc_datetime_usec, null: false, default: fragment("now()")
    end

    create unique_index(:users, [:email], name: "users_unique_email_index")

    create table(:tweets, primary_key: false) do
      add :id, :uuid, null: false, primary_key: true
      add :text, :text, null: false
      add :visibility, :text
      add :inserted_at, :utc_datetime_usec, null: false, default: fragment("now()")
      add :updated_at, :utc_datetime_usec, null: false, default: fragment("now()")

      add :author_id,
          references(:users,
            column: :id,
            name: "tweets_author_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create table(:tokens, primary_key: false) do
      add :created_at, :utc_datetime_usec, null: false, default: fragment("now()")
      add :extra_data, :map
      add :purpose, :text, null: false
      add :expires_at, :utc_datetime, null: false
      add :subject, :text, null: false
      add :jti, :text, null: false, primary_key: true
      add :id, :uuid, null: false, primary_key: true
      add :inserted_at, :utc_datetime_usec, null: false, default: fragment("now()")
      add :updated_at, :utc_datetime_usec, null: false, default: fragment("now()")
    end

    create table(:likes, primary_key: false) do
      add :id, :uuid, null: false, primary_key: true
      add :inserted_at, :utc_datetime_usec, null: false, default: fragment("now()")
      add :updated_at, :utc_datetime_usec, null: false, default: fragment("now()")

      add :user_id,
          references(:users,
            column: :id,
            name: "likes_user_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :tweet_id,
          references(:tweets,
            column: :id,
            name: "likes_tweet_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end

    create unique_index(:likes, [:user_id, :tweet_id], name: "likes_unique_user_and_tweet_index")

    create table(:friend_links, primary_key: false) do
      add :id, :uuid, null: false, primary_key: true
      add :status, :text, null: false, default: "pending"

      add :source_user_id,
          references(:users,
            column: :id,
            name: "friend_links_source_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :destination_user_id,
          references(:users,
            column: :id,
            name: "friend_links_destination_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:friend_links, [:source_user_id, :destination_user_id],
             name: "friend_links_unique_link_index"
           )
  end

  def down do
    drop_if_exists unique_index(:friend_links, [:source_user_id, :destination_user_id],
                     name: "friend_links_unique_link_index"
                   )

    drop constraint(:friend_links, "friend_links_destination_user_id_fkey")

    drop constraint(:friend_links, "friend_links_source_user_id_fkey")

    drop table(:friend_links)

    drop_if_exists unique_index(:likes, [:user_id, :tweet_id],
                     name: "likes_unique_user_and_tweet_index"
                   )

    drop constraint(:likes, "likes_tweet_id_fkey")

    drop constraint(:likes, "likes_user_id_fkey")

    drop table(:likes)

    drop table(:tokens)

    drop constraint(:tweets, "tweets_author_id_fkey")

    drop table(:tweets)

    drop_if_exists unique_index(:users, [:email], name: "users_unique_email_index")

    drop table(:users)
  end
end